name: runner-build

on:
  push:
    branches:
      - main
    paths:
      - runner/**
      - .github/workflows/runner-build.yml
  pull_request:
    paths:
      - runner/**
      - .github/workflows/runner-build.yml
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal

      - name: Build runner
        run: cargo +stable build --locked
        working-directory: ./runner
